### ISSUE TITLE
Zyklischer Bezug zwischen Trainingsystem und Error Management

### ISSUE THREAD

**Issue by LarsLeferenz** [Codethulhu03/UAV#64]
Beide wollen einander im Konstruktor haben, so wird das nix

**Comment by Codethulhu03** [comment]
Vorschlag: hinzufügen des einen Elements durch eine property nach der Initialisierung wenn möglich: siehe connection <-> Basestation (connection.baseStation nach init anstatt übergabe im konstruktor)
